# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
#
# See https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/robot-code-ci.html for more info 

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2022-18.04

    steps:
    - uses: actions/checkout@v3
    
    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Runs a single command using the runners shell
    - name: Compile and run tests on robot code
      run: ./gradlew build
